// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'src/database/models/',
  migrations: {
    path: 'src/database/migrations',
    seed: 'src/database/seed.ts',
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
